### ISSUE TITLE
User input regarding the possibillity to add a note to an agent

### ISSUE THREAD

**Issue by SNATOWA** [DILCISBoard/CITS-ERMS#22]
Hi,

I would suggest a change in the schema to the next version so it will be possible to add a note to an agent.

Kind regards
/Tomas

**Comment by karinbredenberg** [comment]
**The suggestion is:**

Addition of an Notes/note element to the agent element. Update made in both XSD and specification.

**Board members acknowledgment of the issue:**
Tick the box in front of you name to indicate that you have looked at the suggestion.
- [ ] Karin Bredenberg (Kommunalförbundet Sydarkivera, chair)
- [ ] Anders Bo Nielsen (National Archives of Denmark)
- [ ] Anja Paulič (National Archives of Slovenia)
- [ ] Arne-Kristian Groven (National Archives of Norway)
- [ ] Gregor Zavrsnik (Geoarh)
- [ ] Janet Anderson (Highbury Research & Development Ltd.)
- [ ] Maya Bangerter (Swiss Federal Archives)
- [ ] Miguel Ferreira (KEEP Solutions)
- [ ] Stephen Mackey (Penwern Limited)
- [ ] Sven Schlarb (Austrian Institute of Technology)

**Voting**
(Decision making will be carried out on the basis of majority voting by all eligible members of the Board. In the case of a tied vote, decisions will be made at the discretion of the Chair)

Tick the box in front of you name to say yes to the suggestion.
- [ ] Karin Bredenberg (Kommunalförbundet Sydarkivera, chair)
- [ ] Anders Bo Nielsen (National Archives of Denmark)
- [ ] Anja Paulič (National Archives of Slovenia)
- [ ] Arne-Kristian Groven (National Archives of Norway)
- [ ] Gregor Zavrsnik (Geoarh)
- [ ] Janet Anderson (Highbury Research & Development Ltd.)
- [ ] Maya Bangerter (Swiss Federal Archives)
- [ ] Miguel Ferreira (KEEP Solutions)
- [ ] Stephen Mackey (Penwern Limited)
- [ ] Sven Schlarb (Austrian Institute of Technology)

**Comment by karinbredenberg** [comment]
6 DILCIS Board members have acknowledge the issue
5 DILCIS Board members agree with the solution

The update will be published 17th of May 2024.

**Comment by karinbredenberg** [comment]
Update have been published.
