### ISSUE TITLE
User input regarding the possibillity to give the element ClassificationSchema an unbounded occurrence.

### ISSUE THREAD

**Issue by SNATOWA** [DILCISBoard/CITS-ERMS#23]
Hi,

I would suggest a change in the schema to the next version that gives the element classificationSchema an unbounded occurrence.

Kind regards
/Tomas

**Comment by karinbredenberg** [comment]
Possible solution: Addition of max occurance unbounded to the element. Its placed in the control section.

**Comment by karinbredenberg** [comment]
**The suggestion is:**

Update of the occurance of eleemnt classifcationSchema to unbounded

**Board members acknowledgment of the issue:**
Tick the box in front of you name to indicate that you have looked at the suggestion.
- [ ] Karin Bredenberg (Kommunalförbundet Sydarkivera, chair)
- [ ] Anders Bo Nielsen (National Archives of Denmark)
- [ ] Anja Paulič (National Archives of Slovenia)
- [ ] Arne-Kristian Groven (National Archives of Norway)
- [ ] Gregor Zavrsnik (Geoarh)
- [ ] Janet Anderson (Highbury Research & Development Ltd.)
- [ ] Maya Bangerter (Swiss Federal Archives)
- [ ] Miguel Ferreira (KEEP Solutions)
- [ ] Stephen Mackey (Penwern Limited)
- [ ] Sven Schlarb (Austrian Institute of Technology)

**Voting**
(Decision making will be carried out on the basis of majority voting by all eligible members of the Board. In the case of a tied vote, decisions will be made at the discretion of the Chair)

Tick the box in front of you name to say yes to the suggestion.
- [ ] Karin Bredenberg (Kommunalförbundet Sydarkivera, chair)
- [ ] Anders Bo Nielsen (National Archives of Denmark)
- [ ] Anja Paulič (National Archives of Slovenia)
- [ ] Arne-Kristian Groven (National Archives of Norway)
- [ ] Gregor Zavrsnik (Geoarh)
- [ ] Janet Anderson (Highbury Research & Development Ltd.)
- [ ] Maya Bangerter (Swiss Federal Archives)
- [ ] Miguel Ferreira (KEEP Solutions)
- [ ] Stephen Mackey (Penwern Limited)
- [ ] Sven Schlarb (Austrian Institute of Technology)

**Comment by jmaferreira** [comment]
Hi, 

I'm not entirey sure this is a good idea. I would like to pick Carlos Afonso and Miguel Guimarães brains on this topic.

**Comment by hmiguim** [comment]
Hi,

First of all, I'd like to understand the logic behind wanting to have multiple classification schemas. What are the benefits this change will bring to the specification?

I'd also like to add my 2 cents on this matter, the element _classificationSchema_ belongs to the group control, I'd assume that each ERMS may have a classificationSchema describing the record organization. If you add multiple elements of  _classificationSchema_, how do you relate them to the ERMS records?

**Comment by andersbonielsen** [comment]
I have seen systems which allowed more than one classification system in use at the same time, but that only worked because each registration had an attribute identifying the classification system.

**Comment by karinbredenberg** [comment]
7 DILCIS Board members have acknowledge the issue
4 DILCIS Board members agree with the solution

The PR have been updated following the comments and will be part of the next release of the specifications

**Comment by jmaferreira** [comment]
@karinbredenberg 4 out of 10 DILCIS Board members have voted yes. This means that the change has been approved? Explain that math to me please!

**Comment by karinbredenberg** [comment]
7 members acknowledged the suggestion of those 4 voted yes. 4 are more than 3. That's the math.

**Comment by karinbredenberg** [comment]
Update have been published.
