### ISSUE TITLE
User input regarding changing the cardinality for ERMS105 and ERMS108

### ISSUE THREAD

**Issue by SNATOWA** [DILCISBoard/CITS-ERMS#24]
Hi,

I would suggest a change in the specification and the schema to the next version so that ERMS105 (adressline) and ERMS108 (contactLine) gets the cardinality 0..n so you can choose to use only one of them.

Kind regards
/Tomas

**Comment by karinbredenberg** [comment]
Possible solution: A choice to be introduced.

**Comment by karinbredenberg** [comment]
**The suggestion is:**

Update the element addressContactInformation so its possible to just have one of the elements. 

**Board members acknowledgment of the issue:**
Tick the box in front of you name to indicate that you have looked at the suggestion.
- [ ] Karin Bredenberg (Kommunalförbundet Sydarkivera, chair)
- [ ] Anders Bo Nielsen (National Archives of Denmark)
- [ ] Anja Paulič (National Archives of Slovenia)
- [ ] Arne-Kristian Groven (National Archives of Norway)
- [ ] Gregor Zavrsnik (Geoarh)
- [ ] Janet Anderson (Highbury Research & Development Ltd.)
- [ ] Maya Bangerter (Swiss Federal Archives)
- [ ] Miguel Ferreira (KEEP Solutions)
- [ ] Stephen Mackey (Penwern Limited)
- [ ] Sven Schlarb (Austrian Institute of Technology)

**Voting**
(Decision making will be carried out on the basis of majority voting by all eligible members of the Board. In the case of a tied vote, decisions will be made at the discretion of the Chair)

Tick the box in front of you name to say yes to the suggestion.
- [ ] Karin Bredenberg (Kommunalförbundet Sydarkivera, chair)
- [ ] Anders Bo Nielsen (National Archives of Denmark)
- [ ] Anja Paulič (National Archives of Slovenia)
- [ ] Arne-Kristian Groven (National Archives of Norway)
- [ ] Gregor Zavrsnik (Geoarh)
- [ ] Janet Anderson (Highbury Research & Development Ltd.)
- [ ] Maya Bangerter (Swiss Federal Archives)
- [ ] Miguel Ferreira (KEEP Solutions)
- [ ] Stephen Mackey (Penwern Limited)
- [ ] Sven Schlarb (Austrian Institute of Technology)

**Comment by jmaferreira** [comment]
Hi,

I would go a bit further and improve the text of specification to clarify the difference between both these elements:

- ERMS105 (addressline) - The address is made up of several address lines.
- ERMS108 (contacLline) - The contact information is built up with several contact lines

Maybe provide an example of each type.

**Comment by karinbredenberg** [comment]
5 DILCIS Board members have acknowledge the issue
3 DILCIS Board members agree with the solution

The update will be published 17th of May 2024.
