### ISSUE TITLE
Value list for agents

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/CITS-ERMS#26]
There is a need to add contact_person as a type of agent.

**Comment by jmaferreira** [comment]
Hi,

What is the intended use of the new value `contact_person`? What sort of contact should it represent?

Current values already include quite a large list of options:

- administrator
- agent
- archiver
- authorising_person
- borrower
- counterpart
- creator
- custodian
- deliverer
- dispatcher
- editor
- ipp_owner
- main_signatory
- mover
- opening_person
- other_signatory
- owner
- reader
- recipient
- receiver
- relocator
- responsible_person
- sender
- user
- other

**Comment by karinbredenberg** [comment]
The contact_person is coming as input from a use case where none of the roles present is possible to use, it is a person whom is just acting as the contact. Instead of using other and an other description attribute giving contact person as the value the suggestion was made to add the role to simplify the encoding.

**Comment by karinbredenberg** [comment]
6 DILCIS Board members have acknowledge the issue
4 DILCIS Board members agree with the solution

The update will be published 17th of May 2024.
