### ISSUE TITLE
Typo in XSD

### ISSUE THREAD

**Issue by lundst1** [DILCISBoard/CITS-ERMS#33]
The attribute for address types is spelled "adressType" and not "addressType".

**Comment by karinbredenberg** [comment]
Thank you for spotting that! An update will come in the next release.

**Comment by karinbredenberg** [comment]
**The suggestion is:**

Update of the attribute name int the XSD of "adressType" to follow the specifcation and the spelling "addressType".

**Board members acknowledgment of the issue:**
Tick the box in front of you name to indicate that you have looked at the suggestion.
- [ ] Karin Bredenberg (Kommunalförbundet Sydarkivera, chair)
- [ ] Anders Bo Nielsen (National Archives of Denmark)
- [ ] Anja Paulič (National Archives of Slovenia)
- [ ] Arne-Kristian Groven (National Archives of Norway)
- [ ] Gregor Zavrsnik (Geoarh)
- [ ] Janet Anderson (Highbury Research & Development Ltd.)
- [ ] Maya Bangerter (Swiss Federal Archives)
- [ ] Miguel Ferreira (KEEP Solutions)
- [ ] Stephen Mackey (Penwern Limited)
- [ ] Sven Schlarb (Austrian Institute of Technology)

**Voting**
(Decision making will be carried out on the basis of majority voting by all eligible members of the Board. In the case of a tied vote, decisions will be made at the discretion of the Chair)

Tick the box in front of you name to say yes to the suggestion.
- [ ] Karin Bredenberg (Kommunalförbundet Sydarkivera, chair)
- [ ] Anders Bo Nielsen (National Archives of Denmark)
- [ ] Anja Paulič (National Archives of Slovenia)
- [ ] Arne-Kristian Groven (National Archives of Norway)
- [ ] Gregor Zavrsnik (Geoarh)
- [ ] Janet Anderson (Highbury Research & Development Ltd.)
- [ ] Maya Bangerter (Swiss Federal Archives)
- [ ] Miguel Ferreira (KEEP Solutions)
- [ ] Stephen Mackey (Penwern Limited)
- [ ] Sven Schlarb (Austrian Institute of Technology)

**Comment by jmaferreira** [comment]
Hi,

I believe that a more detailed inspection of typos is required. Upon a brief review of the document, I identified the following discrepancies between the specification and the schema:

1. `addressline` versus `addressLine`
2. `contacLline` versus `contactLine`

I suspect there may be additional errors that need to be addressed prior to approving this change. I would recommend that a comprehensive list of typos be compiled before proceeding with acceptance.

**Comment by karinbredenberg** [comment]
Other typos fixed in this update in the textual document:
ERMS14, agencyCode
ERMS15, otherAgencyCode
ERMS16, otherAgencyCode
ERMS21, removal of double erms/control, fix of eventType
ERMS70, ippDuration
ERMS71, ippDuration
ERMS72, ippDuration
ERMS105, addressLine
ERMS106, addressLine
ERMS108, contactLine
ERMS115, disposalScheduled
ERMS132, physical_and_digital
ERMS148, extraId
ERMS191, directionDefinition and otherDirectionDefinition
ERMS249 correction of full element path
ERMS250 correction of full element path

**Comment by karinbredenberg** [comment]
6 DILCIS Board members have acknowledge the issue
5 DILCIS Board members agree with the solution

The updated XML-schema will be published 17th of May 2024.
