### ISSUE TITLE
Suggestion: Split the element addressContactInformation to two elements

### ISSUE THREAD

**Issue by lundst1** [DILCISBoard/CITS-ERMS#34]
Since the content of the element addressContactInformation is a sequence with atleast one element addressLine, agents can't have contact information without having atleast one piece of address information. However, an agent can occurr with just an email address, or some other contact informtion.

Splitting the element addressContactInformation to addressInformation and contactInformation fixes this issue, while still allowing for control that the elements has atleast one child, if they occurr.

**Comment by karinbredenberg** [comment]
Thank you for your suggestion. We will look into it!

**Comment by karinbredenberg** [comment]
This issue is connected to issue #24

**Comment by karinbredenberg** [comment]
Update have been published.
