### ISSUE TITLE
The PDF is scratched!

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/CITS-ERMS#43]
I know... it sounds crazy, but its true. When inspecting the 1.0.0 PDF version of the ERMS CITS we can see that there is a big scratch in the middle of all pages:

<img width="773" alt="Screenshot 2024-04-01 at 13 55 40" src="https://github.com/DILCISBoard/CITS-ERMS/assets/3181302/ed65b553-83f3-41d1-88fa-bd085bdaf8d1">

I can't really explain this... but take a look for your self:

See https://citserms.dilcis.eu/guideline/Guideline_CITS_ERMS_v1.0.pdf

Since this only affects the old version, please feel free to close it.

**Comment by karinbredenberg** [comment]
This is the Guidance document. Not a clue to why. It will be regenerated and published 17th of May 2024.

**Comment by karinbredenberg** [comment]
Update have been published.
