### ISSUE TITLE
Typo in ERMS21

### ISSUE THREAD

**Issue by carlosjepard** [DILCISBoard/CITS-ERMS#45]
There is a typo on sepcification ERMS21 where the "erms/control" is duplicated
![Screenshot from 2024-04-02 10-30-34](https://github.com/DILCISBoard/CITS-ERMS/assets/50378106/aae3cbce-e290-4432-8012-a3945f2d05ed)

**Comment by karinbredenberg** [comment]
Thank you for your comment.
This is being handled in issue #30

**Comment by karinbredenberg** [comment]
Update have been published.
